# Generated by Django 3.2.8 on 2021-11-09 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jackpot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Accepted Bet',
                'ordering': ['accepted_prop__end_date'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('method', models.CharField(blank=True, max_length=100)),
                ('punter', models.CharField(blank=True, max_length=100)),
                ('deposited_on', models.DateTimeField(auto_now_add=True)),
                ('deposit_id', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paypal', models.CharField(blank=True, max_length=100)),
                ('paypal2', models.CharField(blank=True, max_length=100)),
                ('skrill', models.CharField(blank=True, max_length=100)),
                ('skrill2', models.CharField(blank=True, max_length=100)),
                ('bank_transfer', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_current_balance', models.IntegerField()),
                ('new_current_balance', models.IntegerField()),
                ('original_overall_winnings', models.IntegerField()),
                ('new_overall_winnings', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accepted_bet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jackpot.acceptedbet')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_admin', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile Audit',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.IntegerField(default=1000, help_text="The user's current balance. Every time the user settles up, the current balance is reset to zero.")),
                ('overall_winnings', models.IntegerField(default=0, help_text="The user's overall winnings since joining.")),
                ('get_prop_bet_emails', models.BooleanField(default=True)),
                ('get_accepted_bet_emails', models.BooleanField(default=True)),
                ('last_payment', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='ProposedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_text', models.CharField(max_length=256)),
                ('prop_wager', models.IntegerField()),
                ('max_wagers', models.IntegerField()),
                ('remaining_wagers', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('won_bet', models.IntegerField(blank=True, choices=[(1, 'Win'), (-1, 'Loss'), (0, 'Tie')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposed Bet',
                'ordering': ['end_date'],
            },
        ),
        migrations.AddField(
            model_name='acceptedbet',
            name='accepted_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jackpot.proposedbet'),
        ),
        migrations.AddField(
            model_name='acceptedbet',
            name='accepted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
